// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuupPHVEnw57JRj_7T6okKx8sNFHgyJVo',
    appId: '1:313843686185:web:34553e77617f31d0b57538',
    messagingSenderId: '313843686185',
    projectId: 'iot-danish',
    authDomain: 'iot-danish.firebaseapp.com',
    storageBucket: 'iot-danish.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7N6KgNLkHQxDYOmXIX9MdaauHQYeFjeA',
    appId: '1:313843686185:android:cef14be9fb5d8245b57538',
    messagingSenderId: '313843686185',
    projectId: 'iot-danish',
    storageBucket: 'iot-danish.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsIYtnkg_RgJMCEU-eIpDUGWmQHwoBN_M',
    appId: '1:313843686185:ios:1b61cbd112ba1b6bb57538',
    messagingSenderId: '313843686185',
    projectId: 'iot-danish',
    storageBucket: 'iot-danish.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsIYtnkg_RgJMCEU-eIpDUGWmQHwoBN_M',
    appId: '1:313843686185:ios:1b61cbd112ba1b6bb57538',
    messagingSenderId: '313843686185',
    projectId: 'iot-danish',
    storageBucket: 'iot-danish.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuupPHVEnw57JRj_7T6okKx8sNFHgyJVo',
    appId: '1:313843686185:web:a9c94942958821cab57538',
    messagingSenderId: '313843686185',
    projectId: 'iot-danish',
    authDomain: 'iot-danish.firebaseapp.com',
    storageBucket: 'iot-danish.firebasestorage.app',
  );
}
